# Generated by Django 4.1.5 on 2023-01-18 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_like"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Like",
            new_name="IdeaStar",
        ),
    ]
