# Generated by Django 4.1.5 on 2023-01-24 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_like_delete_likes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="like",
            name="user",
        ),
    ]
