# Generated by Django 4.1.5 on 2023-01-24 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_remove_like_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="user",
        ),
    ]
