# Generated by Django 4.1.5 on 2023-01-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="image",
            field=models.ImageField(null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="review",
            name="genre",
            field=models.CharField(
                choices=[
                    ("ACTION", "액션"),
                    ("COMEDY", "코미디"),
                    ("ROMANCE", "로맨스"),
                    ("ANIMATION", "애니메이션"),
                    ("CRIME", "범죄"),
                    ("DRAMA", "드라마"),
                    ("MISTERY", "미스테리"),
                    ("THRILLER", "스릴러"),
                    ("SF", "SF"),
                    ("ADVENTURE", "모험"),
                    ("FANTASY", "판타지"),
                    ("HORROR", "공포"),
                    ("OTHER", "기타"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="running_time",
            field=models.IntegerField(),
        ),
    ]
