# Generated by Django 4.1.5 on 2023-01-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0003_alter_review_genre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="lead_actor",
            field=models.CharField(max_length=24),
        ),
    ]
