# Generated by Django 4.1.5 on 2023-01-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0004_alter_review_lead_actor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="genre",
            field=models.CharField(
                choices=[
                    ("액션", "액션"),
                    ("코미디", "코미디"),
                    ("로맨스", "로맨스"),
                    ("애니메이션", "애니메이션"),
                    ("범죄", "범죄"),
                    ("드라마", "드라마"),
                    ("미스테리", "미스테리"),
                    ("스릴러", "스릴러"),
                    ("SF", "SF"),
                    ("모험", "모험"),
                    ("판타지", "판타지"),
                    ("공포", "공포"),
                    ("기타", "기타"),
                ],
                default="기타",
                max_length=10,
            ),
        ),
    ]
