# Generated by Django 4.1.5 on 2023-01-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0006_alter_review_image_alter_review_stats"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="running_time",
            field=models.CharField(max_length=16),
        ),
    ]
